### PR TITLE
Fix: privilege escalation bug in registration and patch user route

### LINKED ISSUE #29: User Service: User is able to specify role on registration
Currently user is able to specify their desired `role_id` in the request body to the `POST /auth/register` and the `PATCH /users/me` route. In other words, the user is able to perform privilege escalation.

### PR DESCRIPTION
**Pull request by Jovin-Ang**
Closes #29 

Breaking changes:
- Remove `role_id` from `UserCreate` and `UserUpdate` schemas
- Add `role` to UserRead schema
- Add default role_id to user creation (specified via environment variables)

Other changes:
- Refactored config management to use pydantic-settings
- Added new keys in .env
- Added python doc for more classes and methods

Thank you 😄

### CODE REVIEW

File: PeerPrep/src/frontend/pages/auth/Register.tsx [hunk 1]
```diff
@@ -113,7 +113,6 @@ export default function Register() {
         password: formData.password,
         first_name: formData.first_name,
         last_name: formData.last_name,
-        role_id: Roles.User, // Default role (User)
```
Comment (sheenkerr) [inline PeerPrep/src/frontend/pages/auth/Register.tsx:116]: Could you also remove the enums `Roles` at line 15 to 18

**Review by sheenkerr — APPROVED** [review]
LGTM

Just need to add custom error messages later on like:
image
